### ISSUE TITLE
Return response from backend as JSON

### ISSUE THREAD

**Issue by rawad663** [viatra/VIATRA-Generator-Frontend#15]
With the current implementation of the `generateModel()` controller function, the response functionality is handled inside the `generateModel()` function and is simply passed to that function as input.

Example:
```
const controller = require('path_to_controller');
...
(req, res, next) => controller.generateModel(input, res)
```

However, this functionality creates a dependency between the controller function and the router since the response is used in controller.
A better way would be to pass generateModel a function that does the response handling for us:

```
const controller = require('path_to_controller');
...
(req, res, next) => {
    const handleResponse = stdout => response.send({ 
          stdout: stdout
    });
    controller.generateModel(input, handleResponse); // call generateModel here
}
```

**Comment by Mustafakha** [comment]
Done: Files posted (currently using postman) saved through support.savedFilestoDir onto viatra-storage/inputs/"hashedcode"/ where hashed is done through generateUID. Input files are currently viewable on database
TODO:  Modify config files to local database directory -- outputs need to be written (both todo go hand in hand)
