### ISSUE TITLE
Store Input and Output in MongoDB

### ISSUE THREAD

**Issue by rawad663** [viatra/VIATRA-Generator-Frontend#22]
The input and output should be persisted in a clear location on the database.
This task needs to establish the structure of the data to be stored, so that a proper API will be agreed on.

**Comment by fionahang** [comment]
Reference for mongodb sharing connection: [](https://fullstack-developer.academy/sharing-a-mongodb-connection-in-node-js-express/)

**Comment by rawad663** [comment]
So far, the system is able to:
* store input posted by the user to local storage 
* store the generated output to local storage

ToDo:
* Update generateModel to take the multer input path
* Add function that replaces imports in config by new file paths.
