### ISSUE TITLE
Create GET route for resouces

### ISSUE THREAD

**Issue by rawad663** [viatra/VIATRA-Generator-Frontend#28]
Create a `GET` route that will fetch individual resources from the database. This will be used in a few cases:
* Send a URL to the user as a response to a generateModel request which will point to the generated image that was stored on the database.
* Used by the `config` file to import resources (epackage, ...)
* More use cases will need it as we go along...

**This task needs the controller to properly fetch and retrieve data from the database.**

**Comment by fionahang** [comment]
[https://stackabuse.com/read-files-with-node-js/](https://stackabuse.com/read-files-with-node-js/)
